---
- name: Installing Apache MSI
  hosts: win

  tasks:
    - name: Set Windows Powershell
     win_regedit:
      path: HKLM:\SOFTWARE\OpenSSH
      name: DefaultShell
      data: C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe
      type: string
      state: present
